deployment:
  tasks:
    - export DEPLOYPATH=/home/kareem/public_html  # Add /<app_folder> if required
    - /bin/cp <file_name> $DEPLOYPATH                 #Copy specific file to destination from root
    - /bin cp * $DEPLOYPATH                           #copy all from root 
    - /bin cp /dist/* $DEPLOYPATH             #copy all from sub folder root
    - /bin/cp -r * $DEPLOYPATH     